// First-run onboarding state, service-ized like voice-providers.ts: one typed
// JSON file under data/, get/set with patch-merge + validation, wired to
// GET/POST /api/onboarding in serve.ts and folded into /api/bootstrap.
//
// What lives here:
// - profiles: user profiles created through onboarding (the LFG_USERS env
//   roster stays the primary source; these merge into userRoster() so a brand
//   new install with no env config can still create an identity).
// - steps: which onboarding steps are done (profile → agents → first session).
// - completedAt: set once the flow finishes (or is skipped); the frontend
//   gates its full-screen onboarding on this plus "no existing state"
//   (empty roster + empty session list) from the bootstrap payload.
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { PATHS } from "./config.ts";

export type OnboardingProfile = {
  email: string;
  name: string;
  createdAt: string;
  // File name under data/avatars/ when the user uploaded a photo during
  // onboarding; userRoster() serves it via /api/avatars/<file> instead of
  // falling back to Gravatar.
  avatar?: string;
};

export type OnboardingSteps = {
  profile: boolean;
  agents: boolean;
  repo: boolean;
  firstSession: boolean;
};

/**
 * First-run progress for an EMBEDDED (hosted) surface — a managed Computer
 * inside omg — kept deliberately apart from `steps` above.
 *
 * The two flows answer different questions and must not share a field. The
 * open-source flow walks an EMPTY box: make an identity, install agent CLIs,
 * clone a repo. A hosted Computer arrives provisioned, with its identity owned
 * by the host, its roster intentionally empty, and a credential-free agent
 * already seeded — so its first run is about what the person can now DO, not
 * about standing the box up. Folding one into the other would mean every screen
 * branching on whether it was framed.
 *
 * Why this is server-side at all: the embedded connect gate used to track its
 * dismissal in a React `useState`, so "Skip for now" lasted until the next
 * reload and the gate returned on EVERY load until an agent was connected.
 * That turns a first-run into a permanent wall for anyone happy on the free
 * credential-free agent, and is very likely why the host switched the gate off
 * rather than fixing it. Persisted here it is what it claims to be: once.
 */
export type HostedFirstRun = {
  /** Finished (or skipped) the connect + intro screens. */
  introDoneAt: string | null;
  /** Coach steps the person has been walked through. */
  coach: {
    session: boolean;
    schedule: boolean;
  };
};

export type OnboardingState = {
  profiles: OnboardingProfile[];
  steps: OnboardingSteps;
  completedAt: string | null;
  hosted: HostedFirstRun;
};

const DEFAULT_STEPS: OnboardingSteps = {
  profile: false,
  agents: false,
  repo: false,
  firstSession: false,
};

const DEFAULT_HOSTED: HostedFirstRun = {
  introDoneAt: null,
  coach: { session: false, schedule: false },
};

const DEFAULTS: OnboardingState = {
  profiles: [],
  steps: { ...DEFAULT_STEPS },
  completedAt: null,
  hosted: structuredClone(DEFAULT_HOSTED),
};

const filePath = () => join(PATHS.data, "onboarding.json");

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function sanitize(raw: unknown): OnboardingState {
  if (!raw || typeof raw !== "object") return structuredClone(DEFAULTS);
  const p = raw as Partial<OnboardingState>;
  const profiles = Array.isArray(p.profiles)
    ? p.profiles
        .filter(
          (x): x is OnboardingProfile =>
            !!x && typeof x === "object" && typeof (x as OnboardingProfile).email === "string",
        )
        .filter((x) => EMAIL_RE.test(x.email))
        .map((x) => ({
          email: x.email.trim().toLowerCase(),
          name: typeof x.name === "string" ? x.name.trim() : "",
          createdAt: typeof x.createdAt === "string" ? x.createdAt : new Date(0).toISOString(),
          // Avatar file names are generated by setProfileAvatar; reject
          // anything that could path-traverse out of data/avatars.
          ...(typeof x.avatar === "string" && /^[a-z0-9._-]+$/i.test(x.avatar)
            ? { avatar: x.avatar }
            : {}),
        }))
    : [];
  const steps = { ...DEFAULT_STEPS };
  if (p.steps && typeof p.steps === "object") {
    for (const key of Object.keys(DEFAULT_STEPS) as (keyof OnboardingSteps)[]) {
      if (typeof p.steps[key] === "boolean") steps[key] = p.steps[key];
    }
  }
  const hosted = structuredClone(DEFAULT_HOSTED);
  if (p.hosted && typeof p.hosted === "object") {
    if (typeof p.hosted.introDoneAt === "string") hosted.introDoneAt = p.hosted.introDoneAt;
    if (p.hosted.coach && typeof p.hosted.coach === "object") {
      for (const key of Object.keys(DEFAULT_HOSTED.coach) as (keyof HostedFirstRun["coach"])[]) {
        if (typeof p.hosted.coach[key] === "boolean") hosted.coach[key] = p.hosted.coach[key];
      }
    }
  }
  return {
    profiles,
    steps,
    completedAt: typeof p.completedAt === "string" ? p.completedAt : null,
    hosted,
  };
}

export async function getOnboarding(): Promise<OnboardingState> {
  const f = Bun.file(filePath());
  if (!(await f.exists())) return structuredClone(DEFAULTS);
  try {
    return sanitize(JSON.parse(await f.text()));
  } catch {
    return structuredClone(DEFAULTS);
  }
}

// Sync read for users.ts, whose roster helpers (USERS-adjacent) are called
// from synchronous paths and can't await. Same validation/fallback.
export function onboardingProfilesSync(): OnboardingProfile[] {
  try {
    return sanitize(JSON.parse(readFileSync(filePath(), "utf8"))).profiles;
  } catch {
    return [];
  }
}

async function write(state: OnboardingState): Promise<OnboardingState> {
  await mkdir(PATHS.data, { recursive: true });
  await Bun.write(filePath(), JSON.stringify(state, null, 2));
  return state;
}

// Patch-merge steps/completion. `completed: true` stamps completedAt (idempotent),
// `completed: false` clears it (lets a dev re-run the flow).
//
// `hosted` is the embedded surface's own progress and is merged independently:
// `hostedIntroDone: false` and `hostedCoach: {…: false}` are what "restart the
// tour" writes, so the reset has to be expressible, not just the completion.
export async function patchOnboarding(patch: {
  steps?: Partial<OnboardingSteps>;
  completed?: boolean;
  hostedIntroDone?: boolean;
  hostedCoach?: Partial<HostedFirstRun["coach"]>;
}): Promise<OnboardingState> {
  const cur = await getOnboarding();
  const steps = { ...cur.steps };
  if (patch.steps && typeof patch.steps === "object") {
    for (const key of Object.keys(DEFAULT_STEPS) as (keyof OnboardingSteps)[]) {
      if (typeof patch.steps[key] === "boolean") steps[key] = patch.steps[key]!;
    }
  }
  let completedAt = cur.completedAt;
  if (patch.completed === true) completedAt = completedAt ?? new Date().toISOString();
  else if (patch.completed === false) completedAt = null;

  const hosted: HostedFirstRun = {
    introDoneAt: cur.hosted.introDoneAt,
    coach: { ...cur.hosted.coach },
  };
  if (patch.hostedIntroDone === true) {
    hosted.introDoneAt = hosted.introDoneAt ?? new Date().toISOString();
  } else if (patch.hostedIntroDone === false) {
    hosted.introDoneAt = null;
  }
  if (patch.hostedCoach && typeof patch.hostedCoach === "object") {
    for (const key of Object.keys(DEFAULT_HOSTED.coach) as (keyof HostedFirstRun["coach"])[]) {
      if (typeof patch.hostedCoach[key] === "boolean") {
        hosted.coach[key] = patch.hostedCoach[key]!;
      }
    }
  }
  return write({ ...cur, steps, completedAt, hosted });
}

// Create (or update the name of) an onboarding profile. Marks the profile
// step done as a side effect — creating a profile IS completing that step.
// Throws on invalid email so the route can 400 with the message.
export async function addOnboardingProfile(input: {
  email?: unknown;
  name?: unknown;
}): Promise<OnboardingState> {
  const email = typeof input.email === "string" ? input.email.trim().toLowerCase() : "";
  const name = typeof input.name === "string" ? input.name.trim() : "";
  if (!EMAIL_RE.test(email)) throw new Error("expected a valid email");
  const cur = await getOnboarding();
  const existing = cur.profiles.find((p) => p.email === email);
  const profiles = existing
    ? cur.profiles.map((p) => (p.email === email ? { ...p, name: name || p.name } : p))
    : [...cur.profiles, { email, name, createdAt: new Date().toISOString() }];
  return write({ ...cur, profiles, steps: { ...cur.steps, profile: true } });
}

// ------------------------------------------------------------ avatars

export const AVATARS_DIR = () => join(PATHS.data, "avatars");

const AVATAR_EXT: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
};

export const AVATAR_MIME_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
};

const AVATAR_MAX_BYTES = 5 * 1024 * 1024;

// Store an uploaded profile photo for an onboarding profile. File name is
// derived from the email hash (stable, no user input in the path) + extension
// from the validated mime type. Throws with a user-facing message on bad
// input so the route can 400.
export async function setProfileAvatar(
  email: string,
  bytes: Uint8Array,
  mimeType: string,
): Promise<OnboardingState> {
  const ext = AVATAR_EXT[mimeType];
  if (!ext) throw new Error("expected a png, jpeg, webp, or gif image");
  if (!bytes.length) throw new Error("empty image");
  if (bytes.length > AVATAR_MAX_BYTES) throw new Error("image too large (max 5MB)");
  const normalized = email.trim().toLowerCase();
  const cur = await getOnboarding();
  if (!cur.profiles.some((p) => p.email === normalized)) {
    throw new Error("no profile for that email — create the profile first");
  }
  const file = `${createHash("md5").update(normalized).digest("hex")}.${ext}`;
  await mkdir(AVATARS_DIR(), { recursive: true });
  await Bun.write(join(AVATARS_DIR(), file), bytes);
  const profiles = cur.profiles.map((p) =>
    p.email === normalized ? { ...p, avatar: file } : p,
  );
  return write({ ...cur, profiles });
}
